# vit_arch = 'ViT-L-14-CLIP'
vit_arch = 'ViT-B-32-CLIP'

config = {
    'dataset': [
        {
            'name': 'stanford_cars',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/stanford_cars_head.pt',
            'val_fraction': 0.2,
            'batch_size': 32,
            'num_workers': 16,
        },
        {
            'name': 'dtd',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/dtd_head.pt',
            'batch_size': 32,
            'num_workers': 16,
        },
        {
            'name': 'eurosat',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/eurosat_head.pt',
            'batch_size': 32,
            'num_workers': 16,
        },
        {
            'name': 'gtsrb',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/gtsrb_head.pt',
            'val_fraction': 0.2,
            'batch_size': 32,
            'num_workers': 16,
        },
        {
            'name': 'mnist',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/mnist_head.pt',
            'val_fraction': 0.2,
            'batch_size': 32,
            'num_workers': 8,            
        },
        {
            'name': 'resisc45',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/resisc45_head.pt',
            'val_fraction': 0.2,
            'batch_size': 32,
            'num_workers': 16,
        },
        {
            'name': 'sun397',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/sun397_head.pt',
            'val_fraction': 0.2,
            'batch_size': 32,
            'num_workers': 16,
        },
        {
            'name': 'svhn',
            'shuffle_train': True,
            'crop_ratio': 1.0,
            'clip_encodings': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/' + vit_arch + '/svhn_head.pt',
            'val_fraction': 0.2,
            'batch_size': 32,
            'num_workers': 8,
        },
    ],
    'model': {
        'name': 'hf_clip',
        'base_type': "openai/clip-vit-base-patch32",
        'cachedir': '/nethome/becsedi3/flash/logs/kd_distill/cache',
        'bases': [
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/stanford_cars_lora-r16-alpha16-dropout0.1.pt',
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/dtd_lora-r16-alpha16-dropout0.1.pt',
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/eurosat_lora-r16-alpha16-dropout0.1.pt',
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/gtsrb_lora-r16-alpha16-dropout0.1.pt',
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/mnist_lora-r16-alpha16-dropout0.1.pt',
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/resisc45_lora-r16-alpha16-dropout0.1.pt',
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/sun397_lora-r16-alpha16-dropout0.1.pt',
            '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-B-32-CLIP/lora_models/svhn_lora-r16-alpha16-dropout0.1.pt',
        ],
        'ft_config': {
            'type': 'lora',
            'r': 16,
            'lora_alpha': 16,
            'target_modules': ["q_proj", "k_proj", "v_proj", "out_proj"],
            'lora_dropout': 0.1,
            'bias': "none",
        },
    },
    'task_merge_config': {
        'representation': 'svd-vector', 
        'ptm_usage': 'None',
        'sign_resolve_mode': 'sum_of_values',
        's_on_V': True,
        'topK': 100,
        'pre_svd_topK': 100,
        'merge_method': 'ties',
        'mask_method': 'ties',
        'merging_type': 'mean',
        'scaling_coeffs': .6,
        'concat_across_output': True,
        'normalize_Vs_per_model': False,
        'normalize_Vs': None,
        'normalize_Ws_by': None,
        'erase_s': False,
        'merge_other_params': False,
        'label_normalization': None,
        'dare': None,
        'dare_pruning_coeffs': 0.9,
        'whiten': False,
        'normalize_masked_Vs': False,
        'unit_normalize_merge': False,
    },
    'eval_type': 'clip',
    'merging_fn': 'match_tensors_randperm',
    'merging_metrics': ['covariance', 'mean'],
    'finetune_epochs': 0,
    'distill_config': {
        'cache_dir': '/nethome/becsedi3/flash/logs/kd_distill/cache',
        'model_save_dir': '/nethome/becsedi3/flash/model-checkpoints/kd_lora_multidataset',
        'teacher_base_name': "openai/clip-vit-large-patch14",
        'student_base_name': "openai/clip-vit-base-patch32",
        'dataset_name': "svhn",
        'alpha': 0.5,  # Weight for CrossEntropy loss (1.0 - alpha for KD loss)
        'temperature': 2.0,
        # Path to the high-performing teacher model (ViT-L/14 LoRA fine-tuned on mnist)
        'teacher_model_path': '/coc/pskynet2/gstoica3/checkpoints/multiset/openai/ViT-L-14-CLIP/lora_models/mnist_lora-r16-alpha16-dropout0.1.pt',
        # Path to the distilled model (ViT-B/32 LoRA fine-tuned on svhn with distillation from mnist)
        'distilled_model_path': '/nethome/becsedi3/flash/model-checkpoints/kd_lora_multidataset/best_models/KD_svhn_from_mnist_lr_0.0005_epochs_5_wd_5e-05_alpha_0.25_temp_1.0_rank16.pt',
    },
}